Ignore raw `pre_save` signal
DjangoAdminHackers/django-linkcheck pull request #107
Opened 2021-05-09 22:34 UTC by timoludwig

This adds support for the `raw` flag to linkcheck's `pre_save` signal.

If the model is saved exactly as presented (i.e. when loading a fixture), one should not query/modify other records in the database as the database might not be in a consistent state yet (see [documentation](https://docs.djangoproject.com/en/3.2/ref/signals/#pre-save)).

This is my first contribution to this repository, so I'm not sure how you would want this change to be represented in the tests. But if you give me a hint, I'm willing to add test cases for this patch.
Thanks in advance for your feedback and help!

Fixes  #106

2021-05-10 07:04 UTC, claudep commented
Hi Timo, thanks for the report and the patch!
Do you think you would be able to add a fixture to the tests, containing a model like yours that fails in get_absolute_url?

2021-05-13 23:34 UTC, timoludwig commented
@claudep I now added a test case which fails for the current master branch and is fixed with my patch applied.

This was much simpler than I thought because there is another problem with fixtures independent from my special `get_absolute_url()`: The function `instance_pre_save()` tries to query the previous object from the database, but in the case of fixtures, this object does not yet exists, even though it has an id:
https://github.com/DjangoAdminHackers/django-linkcheck/blob/d086a1ef2d8db56c6fe3f4e49f80238b9bcce782/linkcheck/listeners.py#L119
Both problems are fixed if the pre-save method ignores `raw` signals.

2021-05-14 13:15 UTC, claudep requested changes
Thanks a lot! Just two minor suggestions for the patch.

2021-05-14 13:15 UTC, claudep commented on linkcheck/listeners.py
> +def instance_pre_save(sender, instance, raw, **kwargs):
I have a slight preference to using `raw=False` in the signature (technically, this is a kwarg).

2021-05-14 13:15 UTC, claudep commented on linkcheck/tests/test_linkcheck.py
> +        pass
It wouldn't hurt to assert here the presence of the Book instance.

2021-05-14 13:48 UTC, timoludwig commented on linkcheck/tests/test_linkcheck.py
> +        pass
Alright! Like this?

2021-05-14 13:56 UTC, claudep commented on linkcheck/tests/test_linkcheck.py
> +        pass
I guess the first assertion (count = 1) is sufficient.

2021-05-14 14:10 UTC, timoludwig commented on linkcheck/tests/test_linkcheck.py
> +        pass
Ok, I removed the other assertions.

2021-05-14 14:14 UTC, claudep approved these changes

2021-05-14 14:25 UTC, merged

2021-05-14 14:25 UTC, claudep commented
Thanks a lot!