Make templates translatable
DjangoAdminHackers/django-linkcheck pull request #136
Opened 2022-11-22 13:28 UTC by timoludwig

This is not necessarily required for #125 (since I don't use the admin views of this app and only had the translation of the model fields/properties in mind), but for consistency reasons, I think this addition makes sense.

2022-11-22 21:52 UTC, claudep requested changes
Thanks, some points to address.

2022-11-22 21:52 UTC, claudep commented on linkcheck/views.py
> +from django.utils.translation import gettext_lazy as _
I don't think the lazy version is needed in this file.

2022-11-22 21:52 UTC, claudep commented on linkcheck/templates/linkcheck/paginator.html
> +            {% trans "Page" %} {{ pages.number }} {% trans "of" %} {{ pages.paginator.num_pages }}
This is no good practice, segmenting sentences into separate translatable words. Use `{% blocktranslate %}` with variables instead.

2022-11-22 21:52 UTC, claudep commented on linkcheck/templates/linkcheck/coverage.html
> +                    {% if model.is_covered %}{% trans "Yes" %}{% else %}{% trans "No" %}{% endif %}
we could use the `yesno` filter here.

2022-11-22 21:52 UTC, claudep commented on linkcheck/templates/linkcheck/base_linkcheck.html
> +    {% trans "Link Checker" %} {{ block.super }}
Recent Django docs suggests using `translate` instead of `trans`.

2022-11-24 20:12 UTC, claudep commented on linkcheck/templates/linkcheck/suggested_configs.html
> +{% load i18n %}
I don't think the library needs to be imported here.

2022-11-24 20:12 UTC, claudep approved these changes
Apart from the unneeded import, this looks good, thanks!

2022-11-24 20:18 UTC, timoludwig commented on linkcheck/templates/linkcheck/suggested_configs.html
> +{% load i18n %}
You're right, I removed it.

2022-11-24 20:30 UTC, merged